name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint flake8
    - name: Lint with flake8
      run: |
        flake8 src \
          --count \
          --select=E9,F63,F7,F82 \
          --max-complexity=10 \
          --max-line-length=120 \
          --show-source \
          --statistics
    - name: Lint with pylint
      run: |
        pylint src \
          --disable="C0103,C0114,C0115" \
          --fail-under 7.0 \
